[package]
name = "chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
arr_macro = "0.2.1"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx", "ttf"]
